data_params:
  n_rows: 500
  path: '../notebooks/ab_data_new.csv'
  id_col: 'id'
  group_col: 'groups'
  target: 'height_now'
  target_flg: 'bought'
  predictors: ['weight_now']
  numerator: 'clicks'
  denominator: 'sessions'
  covariate: 'height_prev'
  target_prev: 'height_prev'
  predictors_prev: ['weight_prev']
  cluster_col: 'kl-divergence'
  clustering_cols: ['col1', 'col2', 'col3']
  is_grouped: True
simulation_params:
  n_iter: 100
  split_rates: [0.1, 0.2, 0.3, 0.4, 0.5]
  vars: [0, 1, 2, 3, 4, 5]
  extra_params: []
hypothesis_params:
  alpha: 0.05
  beta: 0.2
  alternative: 'two-sided' # less, greater, two-sided
  split_ratios: [0.5, 0.5]
  strategy: 'simple_test'
  strata: 'country'
  strata_weights:
    'US': 0.8
    'UK': 0.2
  n_boot_samples: 200
  n_buckets: 50
  metric_type: 'solid'
  metric_name: 'mean'
result_params:
  to_csv: True
  csv_path: '/app/data/internal/guide/solid_mde.csv'
splitter_params:
  split_rate: 0.5
  name: 'default'
bootstrap_params:
  metric: 'mean'
  num_iterations: 200
aatest_params:
  alpha: 0.05
  method: 'kl-divergence'
  to_cluster: True
  n_clusters: 50